### ISSUE TITLE
Links in ShinyIntro Book

### ISSUE THREAD

**Issue by hathawayj** [debruine/shinyintro#1]
Your GitHub links for `view source` and `edit this on GitHub` don't work.  I am guessing it is the 'pdebruine' instead of 'debruine'.  Thanks for the easy intro to dashboards.  I am going to use it for teaching.

The link out currently returns - https://github.com/pdebruine/shinyintro/blob/master/book/03_inputs.Rmd

**Comment by debruine** [comment]
finally fixed! Sorry that took so long :)
